POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNib3NzZXJ0IiwiaWQiOiI2MjJjZGFlODcyZGJiYmZjYzgwZmZmYTEiLCJpYXQiOjE2NDg1NzgzOTV9.gdcGC4baYakC4Brq0HpSCuUmfV1SLi08Bm5j8acE388

{
    "title": "Hipertextual",
    "author": "Damian Mac dougall",
    "url": "https://hipertextual.com/",
    "likes": 99
}